//! A runtime-independent asynchronous SimConnect client.
//!
//! This crate currently supports native Windows clients only. A dedicated
//! driver thread owns the SimConnect handle and wakes ordinary Rust futures
//! and streams when data arrives.

extern crate self as msfs_async;

#[cfg(windows)]
pub use msfs::sim_connect::{
    ClientDataDefinition, DataDefinition, DataXYZ, Period, SIMCONNECT_OBJECT_ID_USER,
};
#[cfg(windows)]
#[doc(hidden)]
pub use msfs::sys as __sys;
#[cfg(windows)]
pub use msfs_async_derive::{client_data_definition, data_definition};
use std::fmt;

#[cfg(windows)]
mod windows;
#[cfg(windows)]
pub use windows::{
    AsyncSimConnect, ClientDataArea, ExceptionStream, MappedEventSender, MappedEventStream,
    MappedSubscription, ServerException, Subscription, mapped_event_channel,
};

/// The position and orientation components controlled by SimConnect freeze events.
///
/// Freezing a component prevents the simulator from immediately overwriting
/// values a client writes for that component.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct FreezeState {
    /// Freeze latitude and longitude.
    pub latitude_longitude: bool,
    /// Freeze altitude.
    pub altitude: bool,
    /// Freeze pitch, bank, and heading.
    pub attitude: bool,
}

impl FreezeState {
    /// Leave every component under simulation control.
    pub const NONE: Self = Self::new(false, false, false);

    /// Freeze position and attitude so a client can drive all of them.
    pub const ALL: Self = Self::new(true, true, true);

    /// Select individual position and attitude components to freeze.
    pub const fn new(latitude_longitude: bool, altitude: bool, attitude: bool) -> Self {
        Self {
            latitude_longitude,
            altitude,
            attitude,
        }
    }
}

/// A data definition which can safely be copied out of a SimConnect packet.
///
/// # Safety
///
/// Every bit pattern SimConnect can produce for `Self` must be valid, and the
/// type's layout must exactly match its [`DataDefinition`]. The type must not
/// contain references, owning pointers, or fields with destructors. Structures
/// containing Rust `bool` are not valid because SimConnect represents booleans
/// as 32-bit integers.
///
/// This implementation is normally generated by [`data_definition`].
#[cfg(windows)]
pub unsafe trait AsyncDataDefinition: DataDefinition + Copy + Send + 'static {}

/// A client-data definition which can safely cross the driver-thread boundary.
///
/// # Safety
///
/// `Self` must have a stable layout matching its [`ClientDataDefinition`], and
/// every bit pattern that another SimConnect client can write must be valid for
/// the type. Prefer `#[repr(C)]` structures containing integer and float fields.
///
/// This implementation is normally generated by [`client_data_definition`].
#[cfg(windows)]
pub unsafe trait AsyncClientDataDefinition:
    ClientDataDefinition + Copy + Send + 'static
{
}

#[cfg(windows)]
#[doc(hidden)]
pub mod __private {
    use super::DataXYZ;
    use std::marker::PhantomData;

    mod sealed {
        pub trait Sealed {}

        macro_rules! impl_sealed {
            ($($ty:ty),+ $(,)?) => {
                $(impl Sealed for $ty {})+
            };
        }

        impl_sealed!(u8, u16, u32, u64, u128, i8, i16, i32, i64, i128, f32, f64);
        impl Sealed for super::DataXYZ {}
        impl<T: Sealed, const N: usize> Sealed for [T; N] {}
    }

    pub trait SimConnectDatum: sealed::Sealed {}
    impl SimConnectDatum for i32 {}
    impl SimConnectDatum for i64 {}
    impl SimConnectDatum for f32 {}
    impl SimConnectDatum for f64 {}
    impl SimConnectDatum for DataXYZ {}

    pub trait ClientDataDatum: sealed::Sealed {}

    macro_rules! impl_client_data_datum {
        ($($ty:ty),+ $(,)?) => {
            $(impl ClientDataDatum for $ty {})+
        };
    }

    impl_client_data_datum!(u8, u16, u32, u64, u128, i8, i16, i32, i64, i128, f32, f64);
    impl<T: ClientDataDatum, const N: usize> ClientDataDatum for [T; N] {}

    pub struct AssertSimConnectDatum<T: SimConnectDatum>(PhantomData<T>);
    pub struct AssertClientDataDatum<T: ClientDataDatum>(PhantomData<T>);
}

/// Errors produced by the asynchronous client or the SimConnect server.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Error {
    /// A SimConnect function returned a failing HRESULT.
    HResult(i32),
    /// SimConnect reported an asynchronous server-side exception.
    SimConnectException { code: u32, send_id: u32, index: u32 },
    /// A native Windows operation failed.
    Windows(u32),
    /// The data returned by SimConnect was shorter than the requested type.
    InvalidPacket { expected: usize, actual: usize },
    /// The received definition ID did not match the registered type.
    DefinitionMismatch { expected: u32, actual: u32 },
    /// A recurring subscription requires a recurring period.
    InvalidSubscriptionPeriod,
    /// A definition or client name contained an interior NUL byte.
    InvalidCString,
    /// The driver's command or response channel closed unexpectedly.
    DriverStopped,
    /// The driver thread could not be started.
    ThreadStart(String),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::HResult(value) => write!(f, "SimConnect HRESULT {value:#010x}"),
            Self::SimConnectException {
                code,
                send_id,
                index,
            } => write!(
                f,
                "SimConnect exception {code} for send ID {send_id} at argument {index}"
            ),
            Self::Windows(value) => write!(f, "Windows error {value}"),
            Self::InvalidPacket { expected, actual } => write!(
                f,
                "SimConnect packet is too short: expected {expected} bytes, received {actual}"
            ),
            Self::DefinitionMismatch { expected, actual } => write!(
                f,
                "SimConnect definition mismatch: expected {expected}, received {actual}"
            ),
            Self::InvalidSubscriptionPeriod => {
                f.write_str("a subscription requires a recurring SimConnect period")
            }
            Self::InvalidCString => f.write_str("a string contains an interior NUL byte"),
            Self::DriverStopped => f.write_str("the SimConnect driver has stopped"),
            Self::ThreadStart(message) => {
                write!(f, "could not start the SimConnect driver thread: {message}")
            }
        }
    }
}

impl std::error::Error for Error {}

pub type Result<T> = std::result::Result<T, Error>;
