//! A runtime-independent asynchronous SimConnect client.
//!
//! This crate currently supports native Windows clients only. A dedicated
//! driver thread owns the SimConnect handle and wakes ordinary Rust futures
//! and streams when data arrives.

extern crate self as msfs_async;

#[cfg(windows)]
pub use msfs::sim_connect::{
    ClientDataDefinition, DataDefinition, DataXYZ, Period, SIMCONNECT_OBJECT_ID_USER,
};
#[cfg(windows)]
#[doc(hidden)]
pub use msfs::sys as __sys;
#[cfg(windows)]
pub use msfs_async_derive::{client_data_definition, data_definition};
use std::fmt;

#[cfg(any(windows, test))]
mod backend;
#[cfg(any(windows, test))]
mod client_layout;
#[cfg(any(windows, test))]
mod driver;
#[cfg(any(windows, test))]
mod ids;
#[cfg(any(windows, test))]
mod latest;
#[cfg(any(windows, test))]
mod packet;
#[cfg(any(windows, test))]
mod routing;

#[cfg(windows)]
mod native;
#[cfg(windows)]
mod windows;
#[cfg(windows)]
pub use windows::{
    AsyncSimConnect, ClientDataArea, EventStream, ExceptionStream, MappedEventSender,
    MappedEventStream, MappedSubscription, Subscription, mapped_event_channel,
};

/// The position and orientation components controlled by SimConnect freeze events.
///
/// Freezing a component prevents the simulator from immediately overwriting
/// values a client writes for that component.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct FreezeState {
    /// Freeze latitude and longitude.
    pub latitude_longitude: bool,
    /// Freeze altitude.
    pub altitude: bool,
    /// Freeze pitch, bank, and heading.
    pub attitude: bool,
}

/// A recurring cadence accepted by typed subscriptions.
///
/// Unlike the SDK's general `Period` type, this cannot represent one-shot or
/// disabled requests.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum RecurringPeriod {
    /// Deliver changes once per visual frame.
    VisualFrame,
    /// Deliver changes once per simulation frame.
    SimFrame,
    /// Deliver changes once per simulated second.
    Second,
}

/// Behavior when a subscription consumer cannot keep up with incoming data.
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub enum OverflowPolicy {
    /// Preserve queued values and discard newly arriving values while full.
    #[default]
    DropNewest,
    /// Retain only the most recently received value.
    Latest,
}

/// Configuration for a recurring simulation-object subscription.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SubscriptionOptions {
    /// Delivery cadence.
    pub period: RecurringPeriod,
    /// Number of buffered values when using [`OverflowPolicy::DropNewest`].
    pub capacity: usize,
    /// Behavior when values arrive faster than they are consumed.
    pub overflow: OverflowPolicy,
    /// Request only values which changed since the previous delivery.
    pub changed_only: bool,
    /// Number of period events before delivery begins.
    pub origin: u32,
    /// Number of period events between deliveries.
    pub interval: u32,
    /// Maximum deliveries, or zero for no limit.
    pub limit: u32,
}

impl SubscriptionOptions {
    /// Default options for the given cadence.
    pub const fn new(period: RecurringPeriod) -> Self {
        Self {
            period,
            capacity: 32,
            overflow: OverflowPolicy::DropNewest,
            changed_only: true,
            origin: 0,
            interval: 0,
            limit: 0,
        }
    }

    /// Retain only the newest unread value.
    pub const fn latest(mut self) -> Self {
        self.overflow = OverflowPolicy::Latest;
        self
    }
}

impl FreezeState {
    /// Leave every component under simulation control.
    pub const NONE: Self = Self::new(false, false, false);

    /// Freeze position and attitude so a client can drive all of them.
    pub const ALL: Self = Self::new(true, true, true);

    /// Select individual position and attitude components to freeze.
    pub const fn new(latitude_longitude: bool, altitude: bool, attitude: bool) -> Self {
        Self {
            latitude_longitude,
            altitude,
            attitude,
        }
    }
}

/// A data definition which can safely be copied out of a SimConnect packet.
///
/// # Safety
///
/// Every bit pattern SimConnect can produce for `Self` must be valid, and the
/// type's layout must exactly match its [`DataDefinition`]. The type must not
/// contain references, owning pointers, or fields with destructors. Structures
/// containing Rust `bool` are not valid because SimConnect represents booleans
/// as 32-bit integers.
///
/// This implementation is normally generated by [`data_definition`].
#[cfg(windows)]
pub unsafe trait AsyncDataDefinition: DataDefinition + Copy + Send + 'static {}

/// A client-data definition which can safely cross the driver-thread boundary.
///
/// # Safety
///
/// `Self` must have a stable layout matching its [`ClientDataDefinition`], and
/// every bit pattern that another SimConnect client can write must be valid for
/// the type. [`Self::async_definitions`] must describe initialized field bytes
/// within the type and must never identify padding. Prefer `#[repr(C)]`
/// structures containing integer and float fields.
///
/// This implementation is normally generated by [`client_data_definition`].
#[cfg(windows)]
pub unsafe trait AsyncClientDataDefinition:
    ClientDataDefinition + Copy + Send + 'static
{
    #[doc(hidden)]
    fn async_definitions() -> Vec<(usize, usize, u32, f32)>;
}

#[cfg(windows)]
#[doc(hidden)]
pub mod __private {
    use super::DataXYZ;
    use std::marker::PhantomData;

    mod sealed {
        pub trait Sealed {}

        macro_rules! impl_sealed {
            ($($ty:ty),+ $(,)?) => {
                $(impl Sealed for $ty {})+
            };
        }

        impl_sealed!(u8, u16, u32, u64, u128, i8, i16, i32, i64, i128, f32, f64);
        impl Sealed for super::DataXYZ {}
        impl<T: Sealed, const N: usize> Sealed for [T; N] {}
    }

    pub trait SimConnectDatum: sealed::Sealed {}
    impl SimConnectDatum for i32 {}
    impl SimConnectDatum for i64 {}
    impl SimConnectDatum for f32 {}
    impl SimConnectDatum for f64 {}
    impl SimConnectDatum for DataXYZ {}

    pub trait ClientDataDatum: sealed::Sealed {}

    macro_rules! impl_client_data_datum {
        ($($ty:ty),+ $(,)?) => {
            $(impl ClientDataDatum for $ty {})+
        };
    }

    impl_client_data_datum!(u8, u16, u32, u64, u128, i8, i16, i32, i64, i128, f32, f64);
    impl<T: ClientDataDatum, const N: usize> ClientDataDatum for [T; N] {}

    pub struct AssertSimConnectDatum<T: SimConnectDatum>(PhantomData<T>);
    pub struct AssertClientDataDatum<T: ClientDataDatum>(PhantomData<T>);
}

/// A server-side SimConnect exception received after an API call was submitted.
#[non_exhaustive]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ServerException {
    /// Raw `SIMCONNECT_EXCEPTION` value.
    pub code: u32,
    /// SDK send ID associated with the failing call.
    pub send_id: u32,
    /// Zero-based index of the invalid argument, when supplied by the SDK.
    pub index: u32,
}

impl ServerException {
    /// Return the SDK name for this exception code, when known.
    pub fn code_name(&self) -> Option<&'static str> {
        simconnect_exception_name(self.code)
    }
}

impl fmt::Display for ServerException {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.code_name() {
            Some(name) => write!(
                f,
                "SimConnect exception {name} ({}) for send ID {} at argument {}",
                self.code, self.send_id, self.index
            ),
            None => write!(
                f,
                "unknown SimConnect exception {} for send ID {} at argument {}",
                self.code, self.send_id, self.index
            ),
        }
    }
}

impl std::error::Error for ServerException {}

/// Errors produced by the asynchronous client or the SimConnect server.
#[non_exhaustive]
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Error {
    /// A SimConnect function returned a failing HRESULT.
    HResult(i32),
    /// SimConnect reported an asynchronous server-side exception.
    SimConnectException(ServerException),
    /// A native Windows operation failed.
    Windows(u32),
    /// The data returned by SimConnect was shorter than the requested type.
    InvalidPacket { expected: usize, actual: usize },
    /// The received definition ID did not match the registered type.
    DefinitionMismatch { expected: u32, actual: u32 },
    /// A typed client-data handle belongs to a different SimConnect session.
    ClientDataSessionMismatch,
    /// An internal SimConnect identifier space has been exhausted.
    IdExhausted,
    /// A client-data definition contains an offset or size outside its Rust type.
    InvalidClientDataDefinition,
    /// An operation failed and its best-effort rollback failed as well.
    RollbackFailed {
        /// The error which caused rollback to begin.
        operation: Box<Error>,
        /// The error returned while attempting rollback.
        rollback: Box<Error>,
    },
    /// A definition or client name contained an interior NUL byte.
    InvalidCString,
    /// The driver's command or response channel closed unexpectedly.
    DriverStopped,
    /// The driver thread could not be started.
    ThreadStart(String),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::HResult(value) => write!(f, "SimConnect HRESULT {value:#010x}"),
            Self::SimConnectException(exception) => fmt::Display::fmt(exception, f),
            Self::Windows(value) => write!(f, "Windows error {value}"),
            Self::InvalidPacket { expected, actual } => write!(
                f,
                "SimConnect packet is too short: expected {expected} bytes, received {actual}"
            ),
            Self::DefinitionMismatch { expected, actual } => write!(
                f,
                "SimConnect definition mismatch: expected {expected}, received {actual}"
            ),
            Self::ClientDataSessionMismatch => {
                f.write_str("the client-data area belongs to a different SimConnect session")
            }
            Self::IdExhausted => f.write_str("a SimConnect identifier space is exhausted"),
            Self::InvalidClientDataDefinition => {
                f.write_str("a client-data definition is outside its Rust type layout")
            }
            Self::RollbackFailed {
                operation,
                rollback,
            } => write!(
                f,
                "SimConnect operation failed ({operation}) and rollback also failed ({rollback})"
            ),
            Self::InvalidCString => f.write_str("a string contains an interior NUL byte"),
            Self::DriverStopped => f.write_str("the SimConnect driver has stopped"),
            Self::ThreadStart(message) => {
                write!(f, "could not start the SimConnect driver thread: {message}")
            }
        }
    }
}

impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::SimConnectException(exception) => Some(exception),
            Self::RollbackFailed { operation, .. } => Some(operation),
            _ => None,
        }
    }
}

/// Return the SDK name for a known raw SimConnect exception code.
pub fn simconnect_exception_name(code: u32) -> Option<&'static str> {
    const NAMES: &[&str] = &[
        "NONE",
        "ERROR",
        "SIZE_MISMATCH",
        "UNRECOGNIZED_ID",
        "UNOPENED",
        "VERSION_MISMATCH",
        "TOO_MANY_GROUPS",
        "NAME_UNRECOGNIZED",
        "TOO_MANY_EVENT_NAMES",
        "EVENT_ID_DUPLICATE",
        "TOO_MANY_MAPS",
        "TOO_MANY_OBJECTS",
        "TOO_MANY_REQUESTS",
        "WEATHER_INVALID_PORT",
        "WEATHER_INVALID_METAR",
        "WEATHER_UNABLE_TO_GET_OBSERVATION",
        "WEATHER_UNABLE_TO_CREATE_STATION",
        "WEATHER_UNABLE_TO_REMOVE_STATION",
        "INVALID_DATA_TYPE",
        "INVALID_DATA_SIZE",
        "DATA_ERROR",
        "INVALID_ARRAY",
        "CREATE_OBJECT_FAILED",
        "LOAD_FLIGHTPLAN_FAILED",
        "OPERATION_INVALID_FOR_OBJECT_TYPE",
        "ILLEGAL_OPERATION",
        "ALREADY_SUBSCRIBED",
        "INVALID_ENUM",
        "DEFINITION_ERROR",
        "DUPLICATE_ID",
        "DATUM_ID",
        "OUT_OF_BOUNDS",
        "ALREADY_CREATED",
        "OBJECT_OUTSIDE_REALITY_BUBBLE",
        "OBJECT_CONTAINER",
        "OBJECT_AI",
        "OBJECT_ATC",
        "OBJECT_SCHEDULE",
        "JETWAY_DATA",
        "ACTION_NOT_FOUND",
        "NOT_AN_ACTION",
        "INCORRECT_ACTION_PARAMS",
        "GET_INPUT_EVENT_FAILED",
        "SET_INPUT_EVENT_FAILED",
        "EVENT_NAME_RESERVED",
        "INTERNAL",
        "CAMERA_API",
    ];
    NAMES.get(code as usize).copied()
}

pub type Result<T> = std::result::Result<T, Error>;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_known_and_unknown_simconnect_exceptions() {
        assert_eq!(simconnect_exception_name(3), Some("UNRECOGNIZED_ID"));
        assert_eq!(simconnect_exception_name(46), Some("CAMERA_API"));
        assert_eq!(simconnect_exception_name(47), None);

        let exception = ServerException {
            code: 3,
            send_id: 10,
            index: 2,
        };
        assert!(exception.to_string().contains("UNRECOGNIZED_ID"));
        let error = Error::SimConnectException(exception);
        assert_eq!(
            std::error::Error::source(&error).unwrap().to_string(),
            "SimConnect exception UNRECOGNIZED_ID (3) for send ID 10 at argument 2"
        );
    }

    #[test]
    fn latest_subscription_options_are_explicit() {
        let options = SubscriptionOptions::new(RecurringPeriod::SimFrame).latest();
        assert_eq!(options.period, RecurringPeriod::SimFrame);
        assert_eq!(options.overflow, OverflowPolicy::Latest);
        assert!(options.changed_only);
        assert_eq!(options.limit, 0);
    }
}
